### ISSUE TITLE
eval.py运行参数

### ISSUE THREAD

**Issue by peiyingjie** [Vicky-Wil/MONITOR#1]
请问运行eval.py的参数要填什么

**Comment by weixuan-wang123** [comment]
Here are the hyper-parameters.

![Screenshot 2024-10-25 163004](https://github.com/user-attachments/assets/f6f97bba-7b18-4471-92e1-529e596344ed)

**Comment by peiyingjie** [comment]
Thank you for your reply. I am a beginner. Is the "model_dir" filled with the model ID on Hugging Face? Or is it filled with the local model path after downloading the model? However, I still don't quite understand what should be filled in for the "input" and "save" parameters.

> Here are the hyper-parameters.
> 
> ![Screenshot 2024-10-25 163004](https://private-user-images.githubusercontent.com/78357664/380229277-f6f97bba-7b18-4471-92e1-529e596344ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MTQyNjcsIm5iZiI6MTcyOTkxMzk2NywicGF0aCI6Ii83ODM1NzY2NC8zODAyMjkyNzctZjZmOTdiYmEtN2IxOC00NDcxLTkyZTEtNTI5ZTU5NjM0NGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDAzMzkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZDE0YmQ1MzUwMDkwZTM4M2M5NTljNGQ3NDg4ZWVkMTQxMDI2MzZhMzI2Nzc4M2ZjNzczOThkOTY4ZmZlZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.apKy_blAr7GhgajwflRqBKYRe7AAPJFXvK7CAyDXWsw)

**Comment by weixuan-wang123** [comment]
Either the model ID or the checkpoint will work.
The "input" is test file. And the "save" is the file for outputing resutls.
